name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          #!/bin/bash
          set -eux
          
          BRANCH_NAME="${{ github.ref_name }}"
          BRANCH_SUFFIX=$(echo "${INPUT_BRANCH_SUFFIX_MAP}" | jq -r --arg bn "$BRANCH_NAME" '.[$bn] // ""')
          
          if [ ! -f package.json ]; then
            # Error messages to stderr are generally kept for script failure diagnosis
            echo "Error: package.json not found." >&2
            exit 1
          fi
          
          RAW_PACKAGE_VERSION=$(jq -r '.version' package.json)
          
          if [ -z "$RAW_PACKAGE_VERSION" ] || [ "$RAW_PACKAGE_VERSION" == "null" ]; then
            echo "Error: Could not read version from package.json, or version is null." >&2
            exit 1
          fi
          
          PACKAGE_VERSION=$(echo "$RAW_PACKAGE_VERSION" | sed 's/+/-/g')
          TAG_NAME="${PACKAGE_VERSION}${BRANCH_SUFFIX}"
          
          git fetch --tags --force
          
          if ! git rev-parse -q --verify "refs/tags/v${TAG_NAME}" >/dev/null 2>&1; then
            git config user.name "${GIT_USER_NAME}"
            git config user.email "${GIT_USER_EMAIL}"
            git tag -a "v${TAG_NAME}" -m "Version ${TAG_NAME}"
            git push origin "refs/tags/v${TAG_NAME}"
          # else
            # Tag already exists, no action needed and no output necessary
          fi
        env:
          GIT_USER_NAME: github-actions[bot]
          GIT_USER_EMAIL: github-actions[bot]@users.noreply.github.com