name: Bun Package

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          registry-url: https://registry.npmjs.org/
      - uses: justincy/github-action-npm-release@2.0.2
        id: release
      - run: bun publish
        if: steps.release.outputs.released == 'true'
        env:
          NPM_CONFIG_TOKEN: ${{secrets.NPM_TOKEN}}
