name: Bun Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          registry-url: https://registry.npmjs.org/
      - run: bun publish
        env:
          NPM_CONFIG_TOKEN: ${{secrets.NPM_TOKEN}}
