name: Bun Package

on:
  push:
    tags:
      - "*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          registry-url: https://registry.npmjs.org/
      - run: bun publish
        env:
          NPM_CONFIG_TOKEN: ${{secrets.NPM_TOKEN}}
  release:
    runs-on: ubuntu-latest
    needs: [publish-npm]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: spenserblack/actions-tag-to-release@v3.0.0
